/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminVideoRouteImport } from './routes/_authenticated/admin/video'
import { Route as AuthenticatedAdminSpecificationsRouteImport } from './routes/_authenticated/admin/specifications'
import { Route as AuthenticatedAdminAmenitiesRouteImport } from './routes/_authenticated/admin/amenities'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVideoRoute = AuthenticatedAdminVideoRouteImport.update({
  id: '/admin/video',
  path: '/admin/video',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSpecificationsRoute =
  AuthenticatedAdminSpecificationsRouteImport.update({
    id: '/admin/specifications',
    path: '/admin/specifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAmenitiesRoute =
  AuthenticatedAdminAmenitiesRouteImport.update({
    id: '/admin/amenities',
    path: '/admin/amenities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/amenities': typeof AuthenticatedAdminAmenitiesRoute
  '/admin/specifications': typeof AuthenticatedAdminSpecificationsRoute
  '/admin/video': typeof AuthenticatedAdminVideoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/amenities': typeof AuthenticatedAdminAmenitiesRoute
  '/admin/specifications': typeof AuthenticatedAdminSpecificationsRoute
  '/admin/video': typeof AuthenticatedAdminVideoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/amenities': typeof AuthenticatedAdminAmenitiesRoute
  '/_authenticated/admin/specifications': typeof AuthenticatedAdminSpecificationsRoute
  '/_authenticated/admin/video': typeof AuthenticatedAdminVideoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/amenities'
    | '/admin/specifications'
    | '/admin/video'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/amenities'
    | '/admin/specifications'
    | '/admin/video'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/amenities'
    | '/_authenticated/admin/specifications'
    | '/_authenticated/admin/video'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/video': {
      id: '/_authenticated/admin/video'
      path: '/admin/video'
      fullPath: '/admin/video'
      preLoaderRoute: typeof AuthenticatedAdminVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/specifications': {
      id: '/_authenticated/admin/specifications'
      path: '/admin/specifications'
      fullPath: '/admin/specifications'
      preLoaderRoute: typeof AuthenticatedAdminSpecificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/amenities': {
      id: '/_authenticated/admin/amenities'
      path: '/admin/amenities'
      fullPath: '/admin/amenities'
      preLoaderRoute: typeof AuthenticatedAdminAmenitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAmenitiesRoute: typeof AuthenticatedAdminAmenitiesRoute
  AuthenticatedAdminSpecificationsRoute: typeof AuthenticatedAdminSpecificationsRoute
  AuthenticatedAdminVideoRoute: typeof AuthenticatedAdminVideoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAmenitiesRoute: AuthenticatedAdminAmenitiesRoute,
  AuthenticatedAdminSpecificationsRoute: AuthenticatedAdminSpecificationsRoute,
  AuthenticatedAdminVideoRoute: AuthenticatedAdminVideoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
